# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e53fd40e662b949d6980dd4d906a7bd9481b851f529da57b25d87161bfa1adfa9ebcc371708c7d23786dac3c8cf9e500c452346fb26440c812ec7b3c027d47d2

test:
  secret_key_base: f152e1857e3feaa32405802d87b7ebb3654c5e1d36363ae0481492f2dabdd825352bab6335e640743a15171dc001419438361effb14a2972ae4cccd7edc7a630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
